# Local paths settings
log.dir: ".\\logs\\"                            # folder write dump log files to. Will be created if it does not exist.
log.dir.file_retention_seconds: 432000          # retain log files for default of 5 days
log.level: DEBUG                                # level of log verbosity
schedule.state.dir: ".\\ops\\"                  # file written to keep the last run state for schedules
temp.dir: ".\\temp\\"                           # folder to write temporary files to (csv, png for viz exports). Will be created if it does not exist.
temp.dir.file_retention_seconds: 86400          # retain temp files for default of 24 hours, mostly for debugging

# Email settings
smtp.serv: localhost                            # name of the smtp mail server (change for production use; default is only set to "localhost" for ease of testing with PaperCut: https://papercut.codeplex.com/)
smtp.port: 25                                   # port to user for SMTP server (default is 25)
smtp.address.from: vizalerts@yourdomain.com     # default sender for all alerts mail
smtp.address.to: serveradmin@yourdomain.com     # email address of admin to send failures to

smtp.subject: 'ALERT: VizAlerts failed to execute properly'  # subject line in exception emails sent to admin
smtp.ssl: false                                 # use encryption when connecting to SMTP server
smtp.user: null                                 # username for account used to connect to SMTP server (null for no authentication)
smtp.password: null                             # password for account used to connect to SMTP server (null for no authentication)
                                                    # This can either be a plaintext password enclosed in single quotes, e.g. 'myp@ssw0rd'
                                                    # OR it can be a valid path to a .txt file containing the password, e.g. 'c:\users\mcoles\password.txt'
# Tableau Server settings
server: localhost                               # the Tableau Server instance your alerts will reside on. Recommend using the fully-qualified name, e.g. "myserver.mydomain.com"
server.version: 10                              # the major version of Tableau Server that this is running against (just ensures correct URLs in email footers)
server.user: SomeTableauServerUser              # this is ANY user licensed in Tableau Server--it does not need to be an Admin. It is only used to test whether Trusted Tickets work.
                                                    # If you are using Local Authentication, do not prepend domain name to this entry. (e.g., mcoles)
                                                    # If you are using Active Directory Authentication, specify the user as domain\username (e.g., tableau.com\mcoles)
server.ssl: false                               # use HTTPS for Server connections (recommended, but left off by default for testing)
server.certcheck: false                         # if using HTTPS, validate the certificate (recommended, but left off by default for testing)
                                                   # If you turn this on you MUST specify a certificate bundle in server.certfile
server.certfile: null                           # Full path to the set of trusted CA certificates to verify your SSL certificate on Tableau Server in .pem format
                                                    # example: 'c:\\certificates\\cacert.pem'
trusted.useclientip: false                      # use clientip for trusted tickets verification
                                                    # This is optional. Please see http://onlinehelp.tableausoftware.com/current/server/en-us/trusted_auth_optional.htm
trusted.clientip: null                          # IP address of THIS host. Only needed if trusted.useclientip is set to true. Otherwise, just leave it null.

vizalerts.source.viz: 'VizAlerts/AlertList'
vizalerts.viz.site: 'Default'
